

SESSION_EXP_SEC = 3420
SESSION_EXP_MIN = 0
SESSION_EXP_DAYS = 0

REFRESHED_EXP_SEC = 45646
REFRESHED_EXP_MIN = 10
REFRESHED_EXP_DAYS = 7

ENCRYPT_TOKEN = "AKF0n39lohGxRnwmEBMWeJzmlv4ljV2wJ1gMxtptCZYK2WunTKoz0IwOnj0"

ALGORITHMS = ['HS256']
tok = ''


class Settings:
    TITLE = "tITOLO"
    VERSION = "0.1.0"
    SESSION_EXP_SEC = 3420
    SESSION_EXP_MIN = 0
    SESSION_EXP_DAYS = 0
    REFRESHED_EXP_SEC = 45646
    REFRESHED_EXP_MIN = 10
    REFRESHED_EXP_DAYS = 7
    ENCRYPT_TOKEN = "AKF0n39lohGxRnwmEBMWeJzmlv4ljV2wJ1gMxtptCZYK2WunTKoz0IwOnj0"
    ALGORITHMS = ['HS256']
    DESCRIPTION = "Server OIDC (SSO)"
    DOCS_URL = "/"
    REDOC_URL = "/rd"


setting = Settings()
